simplified dependency checking proccess
By doing this, you are not writing the same code again and again.
At the moment, the number of lines has increased by 3, but this is better in the long run because if you decide to add more dependencies, the number of lines will only increase if you use previous method, but this method, it will always stay the same.

diff --git a/sudomy b/sudomy
--- a/sudomy
+++ b/sudomy
@@ -235,11 +235,14 @@ if [ -z "${DOMAIN}" ] ; then
   exit
 fi
 
-## Check depend
-command -v nmap > /dev/null 2>&1 || { echo "Error: require nmap but it's is not installed. Aborting." >&2; exit 1; }
-command -v dig > /dev/null 2>&1 || { echo "Error: require dig but it's is not installed. Aborting." >&2; exit 1; }
-command -v jq > /dev/null 2>&1 || { echo "Error: require jq but it's is not installed. Aborting." >&2; exit 1; }
-command -v httprobe > /dev/null 2>&1 || { echo "Error: require httprobe but it's is not installed. Aborting." >&2; exit 1; }
+## Check dependencies
+dependencies=(nmap dig jq httprobe)
+for dependency in "${dependencies[@]}"; do
+    type -p "$dependency" &>/dev/null || {
+        echo "error: Error: require ${dependency} but it's is not installed. Aborting." >&2
+        exit 1
+	}
+done
 
 if [[ ${PLUGIN_WAPPALYZER} == true ]] ; then
 command -v wappalyzer > /dev/null 2>&1 || { echo "Error: require wappalyzer for identify apps but it's is not installed. Aborting." >&2; exit 1; }
