Apps Identifier added

diff --git a/sudomy b/sudomy
--- a/sudomy
+++ b/sudomy
@@ -172,6 +172,11 @@ args="${1}";
             shift
         ;;
 
+        "-ai"|"--apps-identifier")
+            PLUGIN_WAPPALYZER=true
+            shift
+        ;;
+
         "-ss"|"--screenshot")
             PLUGIN_DOMAIN_SCREENSHOTS=true
             shift
@@ -208,6 +213,7 @@ args="${1}";
             PLUGIN_STATUS_CODE=true
             PLUGIN_RESOLV_SD=true
             PLUGIN_PING_SWEEP=true
+            PLUGIN_WAPPALYZER=true
             shift
         ;;        
     
@@ -234,6 +240,10 @@ command -v nmap > /dev/null 2>&1 || { echo "Error: require nmap but it's is not 
 command -v dig > /dev/null 2>&1 || { echo "Error: require dig but it's is not installed. Aborting." >&2; exit 1; }
 command -v jq > /dev/null 2>&1 || { echo "Error: require jq but it's is not installed. Aborting." >&2; exit 1; }
 command -v httprobe > /dev/null 2>&1 || { echo "Error: require httprobe but it's is not installed. Aborting." >&2; exit 1; }
+
+if [[ ${PLUGIN_WAPPALYZER} == true ]] ; then
+command -v wappalyzer > /dev/null 2>&1 || { echo "Error: require wappalyzer for identify apps but it's is not installed. Aborting." >&2; exit 1; }
+fi
 
 ARG_PARS_LIST(){
 echo -e "\n${BOLD}[${LGREEN}+${RESET}${BOLD}]${RESET} Parsing & Sorting list Domain "
@@ -1273,10 +1283,26 @@ if [[ ${PLUGIN_DOMAIN_SCREENSHOTS} == true ]]; then
 
 fi
 
+if [[ ${PLUGIN_WAPPALYZER} == true ]] ; then
+
+    rm -r ${OUT}/${DATE_LOG}/${DOMAIN}/${RESULT_WAPPALYZER} > /dev/null 2>&1
+
+    echo -e "\n${BOLD}[${LGREEN}+${RESET}${BOLD}]${RESET} Apps Identifier "
+    echo -e "---------------------------------------------\n"
+
+    for WAPPALYZER_SITE in $(cat ${OUT}/${DATE_LOG}/${DOMAIN}/${RESULT_HTTPROBE}) 
+    do
+      WAPPALYZER_RAW=$(wappalyzer ${WAPPALYZER_SITE} 2> /dev/null | jq -r '.applications[] | "\(.name) \(.version)"' | sed 's/ null$//g' | sed 's/,/./g')
+        if [[ ! -z ${WAPPALYZER_RAW} ]]; then
+          echo -e "   ${WAPPALYZER_SITE}"
+          echo -e "${WAPPALYZER_RAW}" | sed 's/^/    - /g'
+          echo ""
+          echo "${WAPPALYZER_SITE};$(echo "${WAPPALYZER_RAW}" | sed ':a;N;$!ba;s/\n/, /g')" >> ${OUT}/${DATE_LOG}/${DOMAIN}/${RESULT_WAPPALYZER}
+        fi
+    done
 
 
-
-
+fi
 
 source lib/template/_template
 
@@ -1347,20 +1373,28 @@ echo -e "${BOLD}${PADDING}${PADDING}\t-${RESET}${BOLD}${RESET}${LGREEN} output/$
 
         if [[ ! -e "${OUT}/${DATE_LOG}/${DOMAIN}/${RESULT_NMAP_HOSTS}" ]] ; then
           COUNT_TOTAL_NMAP=0 
-             _template >> ${OUT}/${DATE_LOG}/${DOMAIN}/report/nmap_tops.html
+              _template >> ${OUT}/${DATE_LOG}/${DOMAIN}/report/nmap_tops.html
         else
               MAKE_TABLE=$(awk 'BEGIN{print ""} {print "<tr>";for(i=1;i<=NF;i++)print "<td>" $i"</td>";print "</tr>"} END{print ""}' ${OUT}/${DATE_LOG}/${DOMAIN}/${RESULT_NMAP_HOSTS})
               echo ${MAKE_TABLE} >> ${OUT}/${DATE_LOG}/${DOMAIN}/report/nmap_tops.html 
               _template >> ${OUT}/${DATE_LOG}/${DOMAIN}/report/nmap_tops.html;fi
 
         if [[ ! -e "${OUT}/${DATE_LOG}/${DOMAIN}/${FINAL_PINGSWEEP}" ]] ; then
-           COUNT_TOTAL_PINGSWEEP=0 
+          COUNT_TOTAL_PINGSWEEP=0 
               _template >> ${OUT}/${DATE_LOG}/${DOMAIN}/report/pingsweep.html
         else
-           COUNT_TOTAL_PINGSWEEP=$(grep -c "LIVE" ${OUT}/${DATE_LOG}/${DOMAIN}/${FINAL_PINGSWEEP})
+          COUNT_TOTAL_PINGSWEEP=$(grep -c "LIVE" ${OUT}/${DATE_LOG}/${DOMAIN}/${FINAL_PINGSWEEP})
               MAKE_TABLE=$(awk 'BEGIN{print ""} {print "<tr>";for(i=1;i<=NF;i++)print "<td>" $i"</td>";print "</tr>"} END{print ""}' ${OUT}/${DATE_LOG}/${DOMAIN}/${FINAL_PINGSWEEP})
               echo ${MAKE_TABLE} >> ${OUT}/${DATE_LOG}/${DOMAIN}/report/pingsweep.html 
               _template >> ${OUT}/${DATE_LOG}/${DOMAIN}/report/pingsweep.html
+        fi
+
+        if [[ ! -e "${OUT}/${DATE_LOG}/${DOMAIN}/${RESULT_WAPPALYZER}" ]]; then
+              _template >> ${OUT}/${DATE_LOG}/${DOMAIN}/report/apps_identifier.html
+        else
+              MAKE_TABLE=$(awk -F ';' '{print "<tr>\n<td>"$1"</td>\n<td>"$2"</td>\n</tr>"}' ${OUT}/${DATE_LOG}/${DOMAIN}/${RESULT_WAPPALYZER})
+              echo -e "${MAKE_TABLE}" >> ${OUT}/${DATE_LOG}/${DOMAIN}/report/apps_identifier.html
+              _template >> ${OUT}/${DATE_LOG}/${DOMAIN}/report/apps_identifier.html
         fi
 
 # INDEX HTML
@@ -1370,7 +1404,6 @@ echo -e "${BOLD}${PADDING}${PADDING}\t-${RESET}${BOLD}${RESET}${LGREEN} output/$
                 sed -i "s/@TOTAL_LIVE_HTTPROBE@/${COUNT_TOTAL_HTTPROBE}/"  ${OUT}/${DATE_LOG}/${DOMAIN}/report/index.html
                   sed -i "s/@TOTAL_LIVE_PINGSWEEP@/${COUNT_TOTAL_PINGSWEEP}/ " ${OUT}/${DATE_LOG}/${DOMAIN}/report/index.html
                     sed -i "s/@TOTAL_200@/${COUNT_TOTAL_200}/ " ${OUT}/${DATE_LOG}/${DOMAIN}/report/index.html
-
 
                       sed -i "s/@PINGSWEEP_VALUE@/${COUNT_TOTAL_PINGSWEEP}/" ${OUT}/${DATE_LOG}/${DOMAIN}/${CHART2}
                         sed -i "s/@HTTPROBE_VALUE@/${COUNT_TOTAL_HTTPROBE}/" ${OUT}/${DATE_LOG}/${DOMAIN}/${CHART2}
